// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJTS__wbJW522SufTjYzqnPX9IPX9ZnmA',
    appId: '1:302482831291:web:60eee89ea7052ec200b69e',
    messagingSenderId: '302482831291',
    projectId: 'social-media-app-af85c',
    authDomain: 'social-media-app-af85c.firebaseapp.com',
    storageBucket: 'social-media-app-af85c.appspot.com',
    measurementId: 'G-5R7VRTG339',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvBcbQA_-ysY8gf7SCBkGGsJIoUtShlzw',
    appId: '1:302482831291:android:4c4583e5345e519700b69e',
    messagingSenderId: '302482831291',
    projectId: 'social-media-app-af85c',
    storageBucket: 'social-media-app-af85c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD-Hpxx8v_ZyOwrRk0lOi69qKD-kUMDSI',
    appId: '1:302482831291:ios:b56dda6ced97ea0a00b69e',
    messagingSenderId: '302482831291',
    projectId: 'social-media-app-af85c',
    storageBucket: 'social-media-app-af85c.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD-Hpxx8v_ZyOwrRk0lOi69qKD-kUMDSI',
    appId: '1:302482831291:ios:0a62116e99a9634800b69e',
    messagingSenderId: '302482831291',
    projectId: 'social-media-app-af85c',
    storageBucket: 'social-media-app-af85c.appspot.com',
    iosBundleId: 'com.example.socialMediaApp.RunnerTests',
  );
}
